### DISCUSSION TITLE
Using Docker Compose to setup lxconsole :-)

### DISCUSSION THREAD

**Discussion by gigadjo** [PenningLabs/lxconsole#34] [Show and tell]
One can run LXConsole using Docker Compose :-)

Use docker-compose.yml formatted as : 

```
version: '3'
services:
  lxconsole:
    image: 'penninglabs/lxconsole:latest'
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      - /path/to/backups:/opt/lxconsole/backups
      - ./certs:/opt/lxconsole/certs
      - ./server:/opt/lxconsole/instance
```

Then connect to your host, as HTTP over port 5000.

Thanks to the developpers for releasing LXConsole, way beter imho than cannonical-ui :-)
