### DISCUSSION TITLE
Password recovery/reset?

### DISCUSSION THREAD

**Discussion by NonaSuomy** [PenningLabs/lxconsole#37] [Q&A]
I had this all running manually but then found the docker compose. I dumped that in portainer and ran the stack. All the folder are the same as before. I was hoping it would just pick up the database where it left off. It brought the server back up but I can't login with my old credentials. It got a different IP address. Is there something more that I would need to do to get back in?

I'm just at a login prompt on the webui after it came back up, no setup etc. I assume that means it's using it's prior data.

```yaml
# LXConsole Container for Docker

services:
  lxconsole:
    container_name: "lxconsole"
    image: 'penninglabs/lxconsole:latest'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.monitor-only=false"
    restart: "always"
    volumes:
      - /opt/docker-storage/lxconsole/certs:/opt/lxconsole/certs
      - /opt/docker-storage/lxconsole/server:/opt/lxconsole/instance
      - /opt/docker-storage/lxconsole/backups:/opt/lxconsole/backups
    hostname: "lxconsole"
    ports:
      - '5000:5000'
    networks:
      dhcp:
        mac_address: "de:ad:be:ef:ca:fe"

networks:
  dhcp:
    name: "dbrv700"
    external: true
```
