### ISSUE TITLE
Docker version stop responding after every Brave browser update on Windows client. Error 500. 

### ISSUE THREAD

**Issue by baiomys** [PenningLabs/lxconsole#24]
Docker service is hosted on separate LAN server, MAC_VLAN network.
All other services hosted on same service IP (same docker-compse) also stop working until restart, which is very disappointing behavior.

```
incus:
    image: 'penninglabs/lxconsole:latest'
    restart: always
    volumes:
      - ./incus/backups:/opt/lxconsole/backups
      - ./incus/certs:/opt/lxconsole/certs
      - ./incus/server:/opt/lxconsole/instance
    networks:
      vlan110:
        ipv4_address: 10.100.100.100
    dns:
      - 1.1.1.1

networks:
  vlan110:
    driver: macvlan
    driver_opts:
      parent: int_gst
    ipam:
      config:
        - subnet: "10.100.100.0/24"
          gateway: "10.100.100.2"
```
